name: Build and Upload Executable

# 允许手动触发
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 选择合适的 Python 版本

      # Step 3: Install dependencies, including pyinstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Use pyinstaller to build the .py file into an executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile your_program.py  # 替换为你的Python文件名
        # 打包后的文件通常会出现在 dist/ 目录中

      # Step 5: Archive the build artifact for upload
      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-executable
          path: dist/your_program  # 替换为打包后的可执行文件路径

      # Step 6: Create a new GitHub release and upload the executable
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'manual-run-${{ github.run_id }}'
          release_name: Manual Run Release
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/your_program  # 替换为你的打包文件路径
          asset_name: your_program  # 替换为你希望的文件名
          asset_content_type: application/octet-stream
